### ISSUE TITLE
bug: np.int() no longer exists.

### ISSUE THREAD

**Issue by jamesdalg** [yekaizhou/duet#11]
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

This looks like a pretty simple fix-- just change np.int to int and it should fix it for current versions of numpy. You could also consider np.int64 (considering the number of bases is greater than 2.7 billion, the largest directly representable number in int32).

**Comment by yekaizhou** [comment]
Dear @jamesdalg,

Thank you very much for pointing this out. We will incorporate this to our next release.

Regards,
Yekai

**Comment by jamesdalg** [comment]
@yekaizhou Let me know when this is addressed. My group is almost specifically asking for SNP aware SV detection and I can't really give them the great phased results duet would bring without it. Sniffles gives a great deal of indels and duet addresses this.

**Comment by yekaizhou** [comment]
The inconsistency of the numpy library is fixed in our latest release v1.0.

**Comment by haraldgrove** [comment]
I'm getting the same error about `AttributeError: module 'numpy' has no attribute 'int'.`  (And no variant calls from Clair3). 

I've tried downloading the latest release (v 1.0) and substituting that for the line `git clone https://github.com/yekaizhou/duet.git` in the installation instructions. And then running `pip install .` in the folder with the new version.

However, I'm still getting the same error so I'm wondering if I'm doing something wrong with the installation of the latest release?

**Comment by yekaizhou** [comment]
Hi @haraldgrove, could you please also try to replace two "np.int" instances to "int" in /your_conda_env/duet/bin/preprocess/CreateTensorPileupFromCffi.py (line 141 and 142)?

**Comment by haraldgrove** [comment]
That seems to have fixed the issue, thanks for the help.
